config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  resources :projects do
    resources :notes
    resources :tasks do
      member do
        patch :toggle
      end
    end
  end

  namespace :api do
    resources :projects#, only: [:index, :show, :create]
  end

  root "home#index"
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :project
  belongs_to :user

  delegate :name, to: :user, prefix: true

  validates :message, presence: true

  scope :search, ->(term) {
    where("LOWER(message) LIKE ?", "%#{term.downcase}%")
  }

  has_one_attached :attachment

  validates :attachment, blob: { content_type: [
    "image/jpeg",
    "image/gif",
    "image/png",
    "application/pdf",
  ]}
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_project
  before_action :project_owner?
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = @project.notes.search(params[:term])
  end

  # TODO: This action is not used.
  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = @project.notes.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = @project.notes.new(note_params.merge(user: current_user))

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note.project, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note.project, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to @note.project, notice: "Note was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:message, :project_id, :attachment)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: [note.project, note], multiple: true) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :message, class: "form-label" %>
    <%= form.text_area :message, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :attachment, class: "form-label" %>
    <%= form.file_field :attachment, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", note.project, class: "btn btn-light", data: { turbo_method: :get, turbo_confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div class="note">
  <div class="note-message">
    <%= simple_format note.message %>
  </div>

  <% if note.attachment.attached? %>
    <div class="note-details">
      <span class="bi bi-file-earmark-fill"></span>
      <%= link_to note.attachment.filename, note.attachment %>
      (<%= note.attachment.content_type %>,
      <%= number_to_human_size(note.attachment.byte_size) %>)
    </div>
  <% end %>

  <h4 class="note-info">
    <%= note.user_name %>,
    <%= full_date(note.created_at) %>
    <%= link_to edit_project_note_path(note.project, note),
                class: "btn btn-light btn-sm btn-inline" do %>
      <span class="bi bi-pencil-fill" aria-hidden="true"></span>
      Edit
    <% end %>
    <%= link_to [note.project, note],
                data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                class: "btn btn-light btn-sm" do %>
      <span class="bi bi-trash" aria-hidden="true"></span>
      Delete
    <% end %>
  </h4>
</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

app/views/notes/index.html.erb
<h1>Search results for <%= params[:term] %></h1>

<%= render @notes %>

<%= link_to "Back to #{@project.name}", @project, class: "btn btn-primary" %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
</div>